name: tg_bot
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  teledart: ^0.6.1
  dotenv: ^4.2.0
  sqlite3: ^2.7.5
  path: ^1.8.0
  telegram: ^0.0.9
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
